from typing import List, Dict, Any
import logging
from pocketflow import Node, Flow
from utils.call_llm import call_llm
from utils.video_processor import get_video_info

# Removed redundant logging.basicConfig to allow main.py to handle it
logger = logging.getLogger(__name__)

class ProcessVideoNode(Node):
    """Download video and extract transcript + frames."""
    def prep(self, shared):
        return shared.get("url", "")
    
    def exec(self, url):
        logger.info(f"Downloading and processing: {url}")
        return get_video_info(url)
    
    def post(self, shared, prep_res, exec_res):
        if "error" in exec_res:
            raise ValueError(exec_res["error"])
        shared["video_info"] = exec_res
        return "default"

class GenerateBlogNode(Node):
    """Generate HTML blog using the complex prompt."""
    def prep(self, shared):
        return {
            "video_info": shared.get("video_info", {}),
            "blog_detail": shared.get("blog_detail", "Extremely detailed, covering every technical nuance and discussion point."),
        }
    
    def exec(self, data):
        video_info = data["video_info"]
        transcript_with_name = video_info.get("transcript_with_name", "")
        blog_detail = data["blog_detail"]
        
        # Style templates (can be customized)
        desired_writing_style = f"{blog_detail} Textbook quality, balanced narrative and technical code blocks. Focus on pedagogical clarity."
        desired_visual_style = "Modern web blog layout, responsive images with captions, clear hierarchy with H1/H2, 16px sans-serif body text."
        
        prompt = f"""
Human: Here is a transcript of a video, including screenshots at different timestamps.

The transcript was generated by an AI speech recognition tool and may contain some errors/infelicities.

Your task is to transform the transcript into an html blog.

The writing style of the blog, including desired balance between text and code is illustrated in a screenshot in <desired_writing_style>.

The visual style of the blog, including page layout, font, headings and image styles are described in <desired_visual_style>.

{transcript_with_name}

<desired_writing_style>
{desired_writing_style}
</desired_writing_style>

<desired_visual_style>
{desired_visual_style}
</desired_visual_style>

This transcript is noisy.  Please rewrite it into an html format for an blog using the following guidelines:

- **Language Adaptability**: Use the SAME LANGUAGE as the provided transcript. If the transcript is in Chinese, the blog must be in Chinese. If it is in English, the blog must be in English.

- **Follow the Structured Outline**: If a "STRUCTURED OUTLINE" is provided in the input, use it as the primary framework for your blog's sections and headings. Ensure each topic in the outline is covered in detail.

- **Granularity & Timestamps**: Do not skip large chunks of time. Create a new section OR paragraph for every major topic shift, approximately every 5 minutes, or whenever a new PPT slide (marked by an image timestamp) is introduced.

- output valid html

- insert section headings and other formatting where appropriate

- use styling to make images, text, code, callouts and the page layout and margins look like the example in <desired_visual_style>

- remove any verbal tics

- if there are redundant pieces of information, only present it once

- rewrite conversational content in the style shown in <desired_writing_style>, including headings to make the narrative structure easier to follow along

- **ADAPTIVE IMAGE INCLUSION**: Each provided screenshot represents a significant change in the video (e.g., a new PPT slide). You should include MOST of these screenshots in your blog where they are relevant to the text. DO NOT limit yourself to a small fixed number; if there is a new slide, include it.

- prefer to include images which display complete code, rather than in progress

- when relevant transcribe important pieces of code and other valuable text

- if an image would help illustrate a part of a transcript, include it

- to include an image, insert a tag <img src="frames/hh_mm_ss.jpg" style="max-width:100%; height:auto; display:block; margin: 20px auto;"> (ie "frames/00_12_35.jpg") copying the exact image timestamp inserted above the image in the transcript

- add captions to images

- do not add any extraneous information: only include what is either mentioned in the transcript or the images

- Timestamps: This is critical. You must include the timestamp for the content at the beginning of each paragraph or section (e.g., **[00:12:35]**). Use the timestamp closest to where the specific information appears in the original transcript.

Your final output should be suitable for inclusion in a textbook.

Assistant: <!DOCTYPE html>
"""
        logger.info("Calling LLM to generate blog...")
        response = call_llm(prompt)
        
        # Ensure it starts with the expected DOCTYPE if the model omitted it after the prefix
        if not response.strip().startswith("<html>") and not response.strip().startswith("<!DOCTYPE"):
            response = "<!DOCTYPE html>\n" + response
            
        return response
    
    def post(self, shared, prep_res, exec_res):
        shared["html_output"] = exec_res
        with open("output.html", "w", encoding="utf-8") as f:
            f.write(exec_res)
        logger.info("Blog generated successfully and saved to output.html")
        return "default"

def create_video_processor_flow():
    """Create the new blog generation flow."""
    process_video = ProcessVideoNode(max_retries=1)
    generate_blog = GenerateBlogNode(max_retries=2)
    
    process_video >> generate_blog
    
    return Flow(start=process_video)
